export * from './platform-nativescript';
export * from './nativescript';
export * from './nativescript_common.module';
// export * from './router/router.module';
export * from './legacy/router';
export * from './application';
export * from './tokens';
export * from './element-registry';
export * from './nativescript_renderer';
export * from './utils/detached-loader';
export * from './forms';
export * from './animations';
export * from './http';
export * from './private_exports';
