export * from './views';
export * from './tokens';
export * from './view-refs';
export { AppOptions, COMMON_PROVIDERS, HmrOptions, NativeScriptDocument, NativeScriptSanitizer, defaultPageFactoryProvider, platformNativeScriptDynamic, platformNativescript } from './platform-nativescript';
export * from './cdk/detached-loader';
export * from './nativescript';
export { ActionBarComponent, ActionBarScope, ActionItemDirective, NavigationButtonDirective } from './cdk/action-bar';
// export * from './cdk/dialog';
export * from './cdk/frame-page';
export * from './cdk/list-view';
export * from './cdk/portal';
export * from './cdk/dialog';
export * from './nativescript-common.module';
// export * from './router/router.module';
export * from './application';
export * from './element-registry';
export * from './nativescript-xhr-factory';
export { EmulatedRenderer, NativeScriptRendererFactory, COMPONENT_VARIABLE as ɵCOMPONENT_VARIABLE, CONTENT_ATTR as ɵCONTENT_ATTR, HOST_ATTR as ɵHOST_ATTR } from './nativescript-renderer';
export * from './utils';
export * from './forms';
export * from './animations';
export * from './http';
export * from './legacy';
export * from './private-exports';
