name: Build

env:
  NX_BRANCH: ${{ github.event.number || github.ref_name }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build affected projects
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'yarn'
      - uses: nrwl/nx-set-shas@v3
      - name: Setup global dependencies
        run: npm i -g yarn
      - name: yarn install
        run: yarn
      - name: Build.all affected
        run: yarn nx affected --target=build --exclude nativescript-demo-ng
